@startuml

skinparam classAttributeIconSize 0

abstract AbstractClassName {
  {abstract} +public_method():void
}

class ClassName {
  #str data
  -private_method()
  #protected_method()
  +public_method():void
}


AbstractClassName <|-- ClassName


class Interface <<interface>> {
  +public_method():void
}

class Implementation {
 +public_method():void
}

Interface <|..right Implementation

Implementation "1"*--"1" ClassName


@enduml
